import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
//         _..._
//         .'     '.      _
//        /    .-""-\\   _/ \\
//      .-|   /:.    |  |   |
//      |  \\  |:.   /.-'-./
//      | .-'-;:__.'    =/
//      .'=  *=|     _.='
//     /   _.  |    ;       
//    ;-.-'|    \\   |        Bem-vindo ao 
//   /   | \\    _\\  _\\           cyberspace
//   \\__/'._;.  ==' ==\\
//            \\    \\   |
//            /    /   /               ✦TrashStar✦✦
//            /-._/-._/
//            \\   '\\  \\
//             '-._/._/     
      <body className={inter.className}>{children}</body>
    </html>
  )
}
